name: Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - run: pnpm install
      - run: pnpm lint

  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - run: pnpm install
      - run: pnpm start -h
